name: build
on:
  push:
    branches:
      - main
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          security-checks: 'vuln,config,secret'
          hide-progress: false
          format: 'table'
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          TRIVY_RUN_AS_PLUGIN: 'aqua'
          GITHUB_TOKEN: ${{ github.token }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "wessupplychain/test:${{ github.sha }}"
      - name: Manifest Generation
        run: |
        export BILLY_SERVER=https://prod-aqua-billy.codesec.aquasec.com
        curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
        curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
        if ! cat install.sh.checksum | sha256sum ; then
        echo "install.sh checksum failed"
        exit 1
        fi
        sh install.sh
        rm install.sh install.sh.checksum
        billy generate \
        --access-token "${{ secrets.GITHUB_TOKEN }}" \
        --aqua-key "${{ secrets.AQUA_KEY }}" \
        --aqua-secret "${{ secrets.AQUA_SECRET }}" \
        --cspm-url "https://api.cloudsploit.com" \
        --artifact-path "wessupplychain/test:${{ env.tag-version }}" 
